U4X-418: Add ability to display the factor of the packaging unit on the stock items and their transactions
METS-Programme/openmrs-module-ugandaemr-commodity pull request #11
Opened 2024-02-28 15:19 UTC by slubwama

https://metsprogramme.atlassian.net/browse/U4X-418

2024-02-29 15:52 UTC, Mwanje commented on owa/package.json
> +  "proxy": "http://127.0.0.1:8084/",
@slubwama Could stick with the default port

2024-03-01 13:53 UTC, akileng56 requested changes

2024-03-01 13:53 UTC, akileng56 commented on owa/src/features/stockItems/StockItemBatchInformation.tsx
> +      quantityuom: `${row.quantityUoM ?? ""} of  ${row.quantityFactor ?? ""}`
``${row.quantityUoM ?? ""} ${row?.quantityFactor ? of ${row?.quantityFactor} : ""}``

2024-03-01 13:53 UTC, akileng56 commented on owa/src/features/stockItems/EditStockItem.tsx
> +                                    return <SelectItem key={uom.uuid} value={uom.uuid} text={`${uom.packagingUomName ?? ""} - ${uom.factor ?? ""}`} />
Same here

2024-03-01 13:53 UTC, akileng56 commented on owa/src/features/stockItems/StockItemQuantities.tsx
> +      quantityuom: `${row.quantityUoM ?? ""} of  ${row.quantityFactor ?? ""}`
Same here

2024-03-01 13:53 UTC, akileng56 commented on owa/src/features/stockItems/StockItemQuantities.tsx
> +                  <TableCell>{total?.quantityUoM ?? ""} of {total?.quantityFactor ?? ""}</TableCell>
Same here

2024-03-01 13:53 UTC, akileng56 commented on owa/src/features/stockOperations/StockOperationItemsTable.tsx
> +                                                {!canEdit && (row?.stockItemPackagingUOMName)+"-"+(row?.stockItemPackagingUOMFactor)}
Same here

2024-03-01 13:53 UTC, akileng56 commented on owa/src/features/stockOperations/StockOperationItemsTable.tsx
> +                                                    itemToString={item => (item?.display ?? item?.packagingUomName ?? '')+"-"+(item?.factor ?? '')}
Same here

2024-03-01 13:53 UTC, akileng56 commented on owa/src/features/stockOperations/StockOperationItemsTable.tsx
> +                                                        display: (row?.stockItemPackagingUOMName)+"-"+(row?.stockItemPackagingUOMFactor)
Same here

2024-03-01 13:53 UTC, akileng56 commented on owa/src/features/stockItems/StockItemTransactions.tsx
> +      qtyout: stockItemTransaction?.quantity < 0 ? `${(-1 * stockItemTransaction?.quantity)?.toLocaleString()} ${stockItemTransaction?.packagingUomName ?? ""} of ${stockItemTransaction?.packagingUomF
Same here

2024-03-01 13:53 UTC, akileng56 commented on owa/src/features/stockItems/StockItemTransactions.tsx
> +      qtyin: stockItemTransaction?.quantity >= 0 ? `${stockItemTransaction?.quantity?.toLocaleString()} ${stockItemTransaction?.packagingUomName ?? ""} of ${stockItemTransaction?.packagingUomFactor ?
Same here

2024-03-01 13:53 UTC, akileng56 commented on owa/src/features/stockItems/StockItemTable.tsx
> +      reorderLevel: stockItem?.reorderLevelUoMName && stockItem?.reorderLevel ? `${stockItem?.reorderLevel?.toLocaleString()} ${stockItem?.reorderLevelUoMName} of ${stockItem?.reorderLevelUoMFactor}`
Same here

2024-03-01 13:53 UTC, akileng56 commented on owa/src/features/stockItems/StockItemTable.tsx
> +      defaultStockOperationsUoMName: `${stockItem?.defaultStockOperationsUoMName} of ${stockItem?.defaultStockOperationsUoMFactor}`,
Same here

2024-03-03 21:32 UTC, slubwama commented
@akileng56 @Mwanje  resolved all your comments

2024-03-05 12:48 UTC, merged